services:
  jobmanager:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: flink-rtcef:python-env
    platform: linux/amd64
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - PYTHONPATH=/opt/flink/python_code
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        env.log.dir: /opt/flink/log
    volumes:
      - ./Wayeb/cef/target/scala-2.12/wayeb-0.6.0-SNAPSHOT.jar:/opt/flink/lib/wayeb.jar
      - ./data:/opt/flink/data  # Mounting data folder to /opt/flink/data container-side
      - ./python:/opt/flink/python_code # Mount python code

  taskmanager:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: flink-rtcef:python-env
    platform: linux/amd64
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - PYTHONPATH=/opt/flink/python_code
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        env.log.dir: /opt/flink/log
    volumes:
      - ./Wayeb/cef/target/scala-2.12/wayeb-0.6.0-SNAPSHOT.jar:/opt/flink/lib/wayeb.jar
      - ./data:/opt/flink/data  # Mounting data folder here is critical
      - ./python:/opt/flink/python_code