services:
  jobmanager:
    image: apache/flink:1.17-java11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        env.log.dir: /opt/flink/log
    volumes:
      - ./Wayeb/cef/target/scala-2.12/wayeb-0.6.0-SNAPSHOT.jar:/opt/flink/lib/wayeb.jar
      - ./data:/opt/flink/data  # Mounting data folder to /opt/flink/data container-side

  taskmanager:
    image: apache/flink:1.17-java11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        env.log.dir: /opt/flink/log
    volumes:
      - ./Wayeb/cef/target/scala-2.12/wayeb-0.6.0-SNAPSHOT.jar:/opt/flink/lib/wayeb.jar
      - ./data:/opt/flink/data  # Mounting data folder here is critical
